version: '2'
services:
    casdemo-app:
        image: casdemo
        external_links:
            - casdemo-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/casdemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    casdemo-postgresql:
        extends:
            file: postgresql.yml
            service: casdemo-postgresql
