version: '2'
services:
    casdemo-postgresql:
        container_name: casdemo-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/casdemo/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=casdemo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
